### ISSUE TITLE
 have HF repos not show up if they were inserted more than n days ago

### ISSUE THREAD

**Issue by zeke** [andreasjansson/python-repos#1]
<img width="679" alt="Screenshot 2023-04-17 at 8 43 10 PM" src="https://user-images.githubusercontent.com/2289/232665777-114f16bd-aeb1-4d94-883b-41e8a89dcc34.png">

**Comment by andreasjansson** [comment]
This is as fixed as it can be, by using "inserted_at" and upserts.
